version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: postgres_urbano
    restart: always
    environment:
      POSTGRES_USER: admin_urbano
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: db_desarrollo_urbano
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql